### ISSUE TITLE
Is*JustReleased function for Actions?

### ISSUE THREAD

**Issue by harbdog** [quasilyte/ebitengine-input#25]
It would be great to be able to have an `ActionIsJustReleased` function, just like ebitengine's inpututil package which provides `IsKeyJustReleased`, `IsMouseButtonJustReleased`, and `IsGamepadButtonJustReleased`.

**Comment by quasilyte** [comment]
There have been a couple of times I needed this as well.
I think this is a reasonable feature to have.

**Comment by quasilyte** [comment]
OK, I bumped into a situation where I need it.
I'll try to implement it.

**Comment by quasilyte** [comment]
As an off-topic, can we add https://github.com/harbdog/pixelmek-3d to the list of library users? :)
It's in the readme.

**Comment by harbdog** [comment]
I may be moving the project under a general area soon, trying to get it ready for a playable alpha first though.

**Comment by quasilyte** [comment]
I rolled out the initial implementation.
Please let me know if it fits your use case.
If it's good enough for now, we can resolve this issue and keep the new related issues I created as follow-ups.

**Comment by harbdog** [comment]
Works like a charm, just replaced the janky function I was using! Thanks!

https://github.com/harbdog/pixelmek-3d/pull/30
