### ISSUE TITLE
Request: An example loading a key map from a file

### ISSUE THREAD

**Issue by mcarpenter622** [quasilyte/ebitengine-input#6]
It would be awesome to see a small example where you load the key map from a file.

**Comment by quasilyte** [comment]
This is something I wanted to implement for a while now.
I'll try to figure out a solution and share it here with you along with an example.
Stay tuned.

**Comment by quasilyte** [comment]
https://github.com/quasilyte/ebitengine-input/blob/master/_examples/configfile/keymap.json
Here is an example.

Although I don't know how to solve the action=>string step properly.
`stringer` can't help with an external type like `input.Action`.

**Comment by mcarpenter622** [comment]
Thank you!
